[package]
name = "zini"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anymap = "0.12.1"
chrono = "0.4.31"
diesel = { version = "2.1.4", features = ["chrono", "postgres", "r2d2"] }
prism_client = { git = "https://github.com/kraemahz/prism.git", branch = "phase2" }
serde = "1.0.193"
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
console-subscriber = "0.2.0"
warp = "0.3.6"
